YellowMovieProject/Models/Movie.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace YellowMovieProject.Models
{
    public class Movie
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "{0} is required.")]
        [StringLength(maximumLength: 100, MinimumLength = 1, ErrorMessage = "{0} has min 1 and max 100 characters")]
        public string Title { get; set; }


        [Required(ErrorMessage = "{0} is required.")]
        [StringLength(maximumLength: 100, MinimumLength = 2, ErrorMessage = "{0} has min 2 and max 100 characters")]
        public string Director { get; set; }


        [Display(Name = "Release year")]
        [Range(1888, 2023, ErrorMessage = "{0} is between 1888 and 2023.")]
        [Required(ErrorMessage = "{0} is required.")]
        public int ReleaseYear { get; set; }


        [Required(ErrorMessage = "{0} is required.")]
        [Range(1, 1999, ErrorMessage = "{0} should be between 1 and 1999")]
        public double Price { get; set; }


        [Display(Name = "Poster URL")]
        public string PosterURL { get; set; } //Poster image suffix https://image.tmdb.org/t/p/w400/

        public virtual ICollection<OrderRow> OrderRows { get; set; } //For finding orderrows containing certain movies (receipts, etc.)

        public Movie()
        {
            OrderRows = new List<OrderRow>();

        }
    }
}

YellowMovieProject/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using YellowMovieProject.Data;
using YellowMovieProject.Models;
using YellowMovieProject.Services;

namespace YellowMovieProject.Controllers
{
    public class MovieController : Controller
    {

        MovieService movieService = new MovieService();

        // GET: Movie
        public ActionResult Index()
        {
            Order newOrder = new Order();

            return View();
        }
        public ActionResult ListAllMovies(string currentPage)
        {
            if (currentPage == null || currentPage == "")
            {
                return View(this.GetMPH(1));
            }
            else
            {

                return View(this.GetMPH(int.Parse(currentPage)));
            }

        }

        //[HttpPost]
        //public ActionResult ListAllMovies(int? currentPage)
        //{            
        //    return View(this.GetMPH(currentPage));
        //}

        private MoviePaginationHelper GetMPH(int? currentPage)
        {
            int maxResults = 10;
            MoviePaginationHelper MPH = new MoviePaginationHelper();

            MPH.CurrentPageIndex = currentPage ?? 1;
            MPH.Movies = movieService.MovieList(MPH);

            MPH.PageCount = (int)Math.Ceiling((double)(movieService.MovieList().Count()) / Convert.ToDouble(maxResults));

            return MPH;
        }
        public ActionResult SearchMovies(string search)
        {
            return View(movieService.SearchMovie(search));
        }

        [HttpGet] //HttpGet is implicated if empty
        public ActionResult AddMovie()
        {
            Movie addMov = new Movie();
            return View(addMov);
        }

        [HttpPost]
        public ActionResult AddMovie(Movie model)
        {
            if (ModelState.IsValid)
            {
                movieService.MovieAdd(model);
                ModelState.Clear();
                Movie movie = new Movie()
                {
                    Title = string.Empty,
                    Director = string.Empty,
                    ReleaseYear = 0,
                    Price = 0,
                    PosterURL = string.Empty
                };
                model = movie;
                ViewBag.AddMovieSuccessMessage = "Movie added successfully.";
            }
            return View(model);
        }
    }
}

YellowMovieProject/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using YellowMovieProject.Models;
using YellowMovieProject.Services;

namespace YellowMovieProject.Controllers
{

    public class ShoppingCartController : Controller

    {
        CustomerService customerService = new CustomerService();
        MovieService movieService = new MovieService();
        OrderService orderService = new OrderService();

        //Class to receive MovieId from Add to Cart button
        public class MovieId
        {
            public int Id { get; set; }
        }

        //Class to receive most updated list from Shopping Cart Index view
        public class shopList
        {
            public List<int> MovieIds { get; set; }
            public List<int> Quantities { get; set; }

        }
        // GET: ShoppingCart
        public ActionResult Index()
        {
            List<int> shoppingList = (List<int>)Session["shoppingList"];
            List<OrderRow> cartRows = new List<OrderRow>();
            double total = 0;

            if (shoppingList != null)
            {
                foreach (int itemId in shoppingList)
                {
                    var movieInList = cartRows.Find(m => m.MovieId == itemId);
                    if (movieInList != null)
                    {
                        movieInList.Quantity++;
                        total += movieInList.Price;
                    }
                    else
                    {
                        OrderRow shoppingItem = new OrderRow();
                        shoppingItem.MovieId = itemId;
                        shoppingItem.Movie = movieService.MovieFind(itemId);
                        shoppingItem.Quantity = 1;
                        shoppingItem.Price = shoppingItem.Movie.Price;
                        total += shoppingItem.Price;
                        cartRows.Add(shoppingItem);
                    }

                }
            }

            ViewBag.Total = total;

            return View(cartRows);
        }

        // Action to receive Ajax request from Add to Cart button event 
        [HttpPost]
        public ActionResult PostFromAjax(MovieId movieId)
        {
            if (Session["shoppingList"] == null)
            {
                List<int> shoppingList = new List<int>();
                shoppingList.Add(movieId.Id);
                Session["shoppingList"] = shoppingList;
                Session["shoppingCount"] = 1;
            }
            else
            {
                List<int> shoppingList = (List<int>)Session["shoppingList"];
                shoppingList.Add(movieId.Id);
                Session["shoppingList"] = shoppingList;
                Session["shoppingCount"] = shoppingList.Count;
            }

            return Json(new { Value = Session["shoppingCount"] });
        }

        //Action to receive updated Shopping Cart items from Shopping Cart index View
        //and create shopping cart list in Session object
        [HttpPost]
        public ActionResult updateCart(shopList shopList)
        {
            if (shopList != null)
            {
                List<int> shoppingList = new List<int>();
                for (int i = 0; i < shopList?.MovieIds?.Count; i++)
                {
                    for (int j = 0; j < shopList.Quantities[i]; j++)
                    {
                        shoppingList.Add(shopList.MovieIds[i]);
                    }
                }
                Session["shoppingList"] = shoppingList;
                Session["shoppingCount"] = shoppingList.Count;
                return Json(new { Value = Session["shoppingCount"] });
            }
            else
            {
                Session.Contents.Clear();
                return Json(new { Value = 0 });
            }

        }


        //Action to check if user exists by checking its email or phone number
        public ActionResult checkUserContact(string contact)
        {
            contact = contact.ToLower().Trim();
            if (contact == null || contact.Length == 0)
            {
                return RedirectToAction("AddDetail", "Customer");
            }

            Customer customer = customerService.CustomerFind(contact);
            if (customer == null)
            {
                return RedirectToAction("AddDetail", "Customer");
            }

            TempData["customerId"] = customer.Id;

            return RedirectToAction("OrderPlacement", "Order");
        }

    }
}

YellowMovieProject/Views/Movie/AddMovie.cshtml
@model YellowMovieProject.Models.Movie

@{
    ViewBag.Title = "Add movie";
}


<section class="h-100" style="background-color: #eee;">
    <div class="container h-100 py-5">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-10">
                <div class="card p-4 mb-4 border-3">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            <h4>Add new movie</h4>
                            <hr />
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="row justify-content-start">
                            <div class="form-group col-sm-12 col-md-10 col-lg-8">
                                @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2 required" })
                                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })

                            </div>

                            <div class="form-group col-sm-12 col-md-10 col-lg-8">
                                @Html.LabelFor(model => model.Director, htmlAttributes: new { @class = "control-label col-md-2  required" })
                                @Html.EditorFor(model => model.Director, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Director, "", new { @class = "text-danger" })
                            </div>

                            <div class="row col-sm-12 col-md-10 col-lg-8 pe-0">
                                <div class="form-group col-sm-6 pe-0">
                                    @Html.LabelFor(model => model.ReleaseYear, htmlAttributes: new { @class = "control-label  required" })
                                    @Html.EditorFor(model => model.ReleaseYear, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.ReleaseYear, "", new { @class = "text-danger" })
                                </div>


                                <div class="form-group col-sm-6 pe-0">
                                    @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label  required" })
                                    @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control", @type = "number", @step = "0.01" } })
                                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                                </div>
                            </div>


                            <div class="form-group col-sm-12 col-md-10 col-lg-8">
                                @Html.LabelFor(model => model.PosterURL, htmlAttributes: new { @class = "control-label col-sm-9" })
                                @Html.EditorFor(model => model.PosterURL, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.PosterURL, "", new { @class = "text-danger" })
                            </div>

                            @*--- Buttons ---*@
                            <div class="row justify-content-center mt-4">
                                <div class="col-12 col-xs-8 col-sm-7 col-lg">
                                    <button type="button" title="Go back to shopping cart" onclick="history.back()"
                                            class="btn btn-secondary btn-lg px-3 m-1 col-12">
                                        Go back
                                    </button>
                                </div>

                                <div class="col-12 col-xs-8 col-sm-7 col-lg">
                                    <button title="Will empty form" class="btn btn-danger btn-lg px-3 m-1 col-12"
                                            type="reset">
                                        Reset
                                    </button>
                                </div>
                                <div class="col-12 col-xs-8 col-sm-7 col-lg">
                                    <button title="Continue to payment" class="btn btn-success btn-lg px-3 m-1 col-12"
                                            type="submit">
                                        Continue
                                    </button>
                                </div>
                            </div>
                            
                        </div>
                        </div>
                    }
                    <br />
                    <h3 class="text-success">@ViewBag.AddMovieSuccessMessage</h3>
                </div>
            </div>
        </div>
    </div>
</section>

YellowMovieProject/Views/Movie/ListAllMovies.cshtml
@model YellowMovieProject.Models.MoviePaginationHelper


<div class="text-center">
    <h2>All Movies</h2>
</div>

    <br />
    <div>
        

            <div class="row justify-content-center row-cols-md-2 row-cols-sm-2 row-cols-xs-1">

                @foreach (var item in Model.Movies)
                {
                    @Html.Partial("_MovieCardPartial", item);
                }
            </div>
            <br />
            <nav aria-label="Page Navigation">
                <ul class="pagination">
                    <li class="page-item">
                        @if(@Model.CurrentPageIndex != 1)
                        {
                            <a class="page-link" href="@Url.Action("ListAllMovies","Movie",new {currentPage=Model.CurrentPageIndex-1})" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                                <span class="sr-only"></span>
                            </a>
                        }
                        else
                        {
                            <a class="page-link" href="#" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                                <span class="sr-only"></span>
                            </a>
                        }
                        
                    </li>
                    @for (int i = 1; i <= Model.PageCount; i++)
                    {
                        if (i != Model.CurrentPageIndex && i > Model.CurrentPageIndex - 4 && i < Model.CurrentPageIndex + 5)
                        {
                            <li class="page-item">
                                <a class="page-link" href="@Url.Action("ListAllMovies","Movie",new {currentPage=i})">@i</a>
                            </li>
                        }
                        else if (i == 1)
                        {
                            <li class="page-item">
                                <a class="page-link" href="@Url.Action("ListAllMovies","Movie",new {currentPage=i})">@i</a>
                            </li>
                            <li class="page-item">
                                <a class="page-link">...</a>
                            </li>
                        }
                        else if (i == Model.PageCount)
                        {
                            <li class="page-item">
                                <a class="page-link">...</a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="@Url.Action("ListAllMovies","Movie",new {currentPage=i})">@i</a>
                            </li>
                        }

                        else if (i == Model.CurrentPageIndex)
                        {
                            <li class="active page-item"><a class="page-link">@i</a></li>
                        }
                    }
                <li class="page-item">
                    @if (@Model.CurrentPageIndex != Model.PageCount)
                    {
                        <a class="page-link" href="@Url.Action("ListAllMovies","Movie",new {currentPage=Model.CurrentPageIndex+1})" aria-label="next">
                            <span aria-hidden="true">&raquo;</span>
                            <span class="sr-only"></span>
                        </a>
                    }
                    else
                    {
                        <a class="page-link" href="#" aria-label="next">
                            <span aria-hidden="true">&raquo;</span>
                            <span class="sr-only"></span>
                        </a>
                    }
                </li>
                </ul>
            </nav>
            
            @*<input type="hidden" id="hfCurrentPageIndex" name="currentPage" />*@
        
        @*<script type="text/javascript">
            function PagerClick(index) {
                document.getElementById("hfCurrentPageIndex").value = index;
                document.forms[1].submit();
            }
        </script>*@
    </div>
    

        

    <script>

    function addToCart(movieId)
    {
        var tmpObj = {
            Id: movieId,
        };

        var req = new XMLHttpRequest();
        req.onload = function () {
            if (req.status >= 200 && req.status < 400 ) {
                document.getElementById("ShoppingListItems").innerHTML = JSON.parse(this.response).Value;
            }
        }
        req.open('POST', '@Url.Action("PostFromAjax", "ShoppingCart")', true);
        req.setRequestHeader('Content-Type', 'application/json');

        req.send(JSON.stringify(tmpObj));
    }
    </script>

YellowMovieProject/Views/Movie/SearchMovies.cshtml
@model IEnumerable<YellowMovieProject.Models.Movie>


<div class="text-center">
    <h2>Search result</h2>
</div>
@if (Model.Count() > 0)
{
    <br />

    <div class="row justify-content-center row-cols-md-2 row-cols-sm-2 row-cols-xs-1">

        @foreach (var item in Model)
        {
            @Html.Partial("_MovieCardPartial", item);
        }
    </div>
}
else
{
    <h4 class="text-danger"> Sorry, no result!</h4>
}
<script>

    function addToCart(movieId)
    {
        var tmpObj = {
            Id: movieId,
        };

        var req = new XMLHttpRequest();
        req.onload = function () {
            if (req.status >= 200 && req.status < 400 ) {
                document.getElementById("ShoppingListItems").innerHTML = JSON.parse(this.response).Value;
            }
        }
        req.open('POST', '@Url.Action("PostFromAjax", "ShoppingCart")', true);
        req.setRequestHeader('Content-Type', 'application/json');

        req.send(JSON.stringify(tmpObj));
    }
</script>